### ISSUE TITLE
Uncaught (in promise) TypeError: Already read

### ISSUE THREAD

**Issue by developer239** [agraboso/redux-api-middleware#118]
When I use this in failure response:

```
getJSON(res).then(
    (json) => new ApiError(res.status, res.statusText, json)
  )
```

I get

```
bundle.js:54039 Uncaught (in promise) TypeError: Already read
    at Object.meta (http://localhost:8080/generated/bundle.js:54039:16)
    at Object.actionWith$ (http://localhost:8080/generated/bundle.js:51151:99)
    at tryCatch (http://localhost:8080/generated/bundle.js:51389:41)
    at Generator.invoke [as _invoke] (http://localhost:8080/generated/bundle.js:51651:23)
    at Generator.prototype.(anonymous function) [as next] (http://localhost:8080/generated/bundle.js:51422:22)
    at tryCatch (http://localhost:8080/generated/bundle.js:51389:41)
    at invoke (http://localhost:8080/generated/bundle.js:51463:21)
    at http://localhost:8080/generated/bundle.js:51471:14
```

**Comment by developer239** [comment]
For anyone getting same error documentation says this about handling failure response:

Failure type descriptors

payload and meta functions will be passed the RSAA action itself, the state of your Redux store, and the raw server response — exactly as for success type descriptors. The error property of dispatched failure FSAs will always be set to true.

For example, if you want the status code and status message of a unsuccessful API call in the meta property of your failure FSA, do the following.

```
{
  [CALL_API]: {
    endpoint: 'http://www.example.com/api/users/1',
    method: 'GET',
    types: [
      'REQUEST',
      'SUCCESS',
      {
        type: 'FAILURE',
        meta: (action, state, res) => {
          if (res) {
            return {
              status: res.status
              statusText: res.statusText
            };
          } else {
            return {
              status: 'Network request failed'
            }
          }
        }
      }
    ]
  }
}
```
By default, failure FSAs will not contain a meta property, while their payload property will be evaluated from

```
(action, state, res) =>
  getJSON(res).then(
    (json) => new ApiError(res.status, res.statusText, json)
  )
```

What is not mentioned is that if you want to use

```
(action, state, res) =>
  getJSON(res).then(
    (json) => new ApiError(res.status, res.statusText, json)
  )
```

* YOU HAVE TO USE PAYLOAD PROPERTY * that might seem to be obvious but it isn't.

```
{
  [CALL_API]: {
    endpoint: 'http://www.example.com/api/users/1',
    method: 'GET',
    types: [
      'REQUEST',
      'SUCCESS',
      {
        type: 'FAILURE',
        payload: (action, state, res) =>
            getJSON(res).then(json => console.log(json)), // THIS WILL GIVE YOU DATA FROM FAILURE RESPONSE
        meta: (action, state, res) => {
          if (res) {
            return {
              status: res.status
              statusText: res.statusText
            };
          } else {
            return {
              status: 'Network request failed'
            }
          }
        }
      }
    ]
  }
}
```

**Comment by developer239** [comment]
To be honest I did not really read the documentation.
