### ISSUE TITLE
fetch error

### ISSUE THREAD

**Issue by dinfyru** [agraboso/redux-api-middleware#225]
i try to disable cors, but it fails
```
    action[RSAA].fetch = async (url, params) => {
      const res = await fetch(url, { ...params, mode: 'no-cors' });
      const returnRes = res.clone();

      return returnRes;
    };
```
Error
```
error: true
meta: undefined
payload: ApiError: 0 - at eval (webpack-internal:///../node_modules/redux-api-middleware/lib/index.umd.js:2507:18)
message: "0 - "
name: "ApiError"
response: undefined
status: 0
statusText: ""
stack: "ApiError: 0 - ↵    at eval (webpack-internal:///../node_modules/redux-api-middleware/lib/index.umd.js:2507:18)"
__proto__: Wrapper
type: "USER_ACTION_GET_INFO_FAILURE"
```

**Comment by nason** [comment]
Hi @dinfyru are you sure this request be made without CORS?

At first glance this error looks like its caused by the request failing due to cross-origin issues
