### ISSUE TITLE
Module Build Failed: Error: Plugin 1 specified in "base" provided an invalid property of "__wrapped"

### ISSUE THREAD

**Issue by peterpme** [agraboso/redux-api-middleware#97]
Hey,

I've never seen this error message before and googling it is tough. I'm using the next branch, building it and seeing this. Has anyone had any issues?

``` bash
ERROR in /Users/peter/Sites/temp/redux-api-middleware/lib/index.js
Module build failed: Error: Plugin 1 specified in "base" provided an invalid property of "__wrapped__"
    at Plugin.init (/Users/peter/Sites/test-labs/uc-frontend/node_modules/babel-core/lib/transformation/plugin.js:138:13)
    at Function.normalisePlugin (/Users/peter/Sites/test-labs/uc-frontend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:147:12)
    at /Users/peter/Sites/test-labs/uc-frontend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:181:30
    at Array.map (native)
    at Function.normalisePlugins (/Users/peter/Sites/test-labs/uc-frontend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:153:20)
    at OptionManager.mergeOptions (/Users/peter/Sites/test-labs/uc-frontend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:245:36)
    at OptionManager.init (/Users/peter/Sites/test-labs/uc-frontend/node_modules/babel-core/lib/transformation/file/options/option-manager.js:383:12)
    at File.initOptions (/Users/peter/Sites/test-labs/uc-frontend/node_modules/babel-core/lib/transformation/file/index.js:223:65)
    at new File (/Users/peter/Sites/test-labs/uc-frontend/node_modules/babel-core/lib/transformation/file/index.js:140:24)
    at Pipeline.transform (/Users/peter/Sites/test-labs/uc-frontend/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/Users/peter/Sites/test-labs/uc-frontend/node_modules/babel-loader/index.js:14:22)
    at /Users/peter/Sites/test-labs/uc-frontend/node_modules/babel-loader/lib/fs-cache.js:145:18
    at ReadFileContext.callback (/Users/peter/Sites/test-labs/uc-frontend/node_modules/babel-loader/lib/fs-cache.js:28:23)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:359:13)
 @ ./src/redux/configureStore.js 10:26-57
```

**Comment by iamakulov** [comment]
Probable solution: https://github.com/lodash/babel-plugin-lodash/issues/83#issuecomment-233941018

**Comment by nason** [comment]
Not sure what this was -- but its been over a year so I'm going to close this out. Feel free to re-open if this is still an issue.
